openapi: 3.0.0
info:
  version: 1.0.0
  title: Bible Notes API
  description: An API to illustrate a note taking app for bible study
servers:
  - url: 'http://localhost:3000'
paths:
  /notes/{noteId}:
    get:
      summary: 'Returns details of a particular note'
      operationId: listNote
      tags:
        - note
      parameters:
        - name: noteId
          in: path
          description: ID of the note
          required: true
          schema:
            type: integer
            format: int32
            example: '1001'
      responses:
        '200':
          description: OK - Details about a note by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad Request - Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Not Found - Item not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
  /notes:
    get:
      summary: 'Get a list of notes from the database' 
      tags: []
      responses:
        '200':
         description: OK - Successful pull of notes
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notes' 
             examples:
               example-1:  
                 value:
                   - noteId: 1001
                     title: Bible Study Notes
                     description: 'Read Psalm 34,35,36 Prov 3-7'
                     createdAt: '2020-03-05T14:07:01.688Z'
                     updatedAt: ''
                   - noteId: 1002
                     title: Bible Study Notes
                     description: 'Read 1 Chron 2:16-20, Prov 9'
                     createdAt: '2020-03-05T14:10:01.688Z'
                     updatedAt: '2020-03-05T14:20:00.000Z'
                   - noteId: 1003
                     title: Bible Study Notes
                     description: 'Verses about salvation - Exodus 15:2, 1 Chron 16:23'
                     createdAt: '2020-03-05T15:05:01.00'
                     updatedAt: '2020-03-10T10:00:00.000Z'
                   - noteId: 1004
                     title: Bible Study Notes
                     description: Read Psalm 118,119
                     createdAt: '2020-04-19T11:45:01.000Z'
                     updatedAt: ''
                   - noteId: 1005
                     title: Bible Study Notes
                     description: Read 1 Kings 2 - 4
                     createdAt: '2020-05-30T09:10:00.00Z'
                     updatedAt: '2020-06-14T09:30:00.00Z'
                   - noteId: 1006
                     title: Bible Study Notes
                     description: Read John 1 - 3
                     createdAt: '2020-06-25T16:40:02.000Z'
                     updatedAt: ''
                   - noteId: 1007
                     title: Bible Study Notes
                     description: Read Ezra
                     createdAt: '2020-10-02T08:15:00.000Z'
                     updatedAt: '2020-10-03T11:30:00.00Z'
                   - noteId: 1008
                     title: Bible Study Notes
                     description: Read Psalm 18:2, Psalm 27:2
                     createdAt: '2020-11-08T14:50:01.688Z'
                     updatedAt: ''
                   - noteId: 1009
                     title: Bible Study Notes
                     description: Read Isaiah 54 before women's group meeting
                     createdAt: '2020-12-18T17:30:01.000Z'
                     updatedAt: ''
                   - noteId: 1010
                     title: Bible Study Notes
                     description: End of year bible study - Psalm 95:1, John 1:1-5
                     createdAt: '2020-03-05T14:07:01.688Z'
                     updatedAt: ''
components:
  schemas:
    Note:
      title: note
      type: object
      required:
        - noteId
      description: Model containing notes information
      properties:
        noteId:
          type: integer
          format: int32
          example: '1001'
        title:
          type: string
          example: 'Notes about Christ'
        description:
          type: string
          example: 'Refer to John 14:25, 2 Chron 16:20, Psalm 34'
        createdAt:
          type: string
          format: date-time
        updatedAt: 
          type: string
          format: date-time
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    BadRequest:
      title: Bad Request
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    NotFound:
      title: Not Found
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
    Notes:
      type: array
      title: notes
      example: '10'
      maximum: 10
      minimum: 4
      items:
        $ref: '#/components/schemas/Note'