openapi: 3.0.0
info:
  version: 1.0.0
  title: Bible Notes API
  description: An API to illustrate a note taking app for bible study
servers:
  - url: 'http://localhost:3000'
paths:
  /notes/{noteId}:
    get:
      summary: 'Sample endpoint: Returns details of a particular note'
      operationId: listNote
      tags:
        - note
      parameters:
        - name: noteId
          in: path
          description: ID of the note
          required: true
          schema:
            type: integer
            format: int32
            example: '1001'
      responses:
        '200':
          description: OK - Details about a note by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Bad Request - Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Not Found - Item not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'  
  /notes:
    get:
      summary: 'Sample Endpont: Returns list of all notes' 
      tags: []
      responses:
        '200':
         description: OK - Successful pull of notes
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notes' 
             examples:
               example-1:  
                 value:
                          
components:
  schemas:
    Note:
        title: note
        type: object
        required:
            - noteId
        description: Model containing notes information
        properties:
            noteId:
                type: integer
                format: int32
                example: '1001'
            title:
                type: string
                example: 'Notes about Christ'
            description:
                type: string
                example: 'Refer to John 14:25, 2 Chron 16:20, Psalm 34'
            createdAt:
                type: string
                format: date-time
            updatedAt: 
                type: string
                format: date-time
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    BadRequest:
        title: Bad Request
        type: object
        properties:
            error:
                type: object
                properties:
                    message:
                        type: string
    NotFound:
        title: Not Found
        type: object
        properties:
            error:
                type: object
                properties:
                    message:
                        type: string
    Notes:
        type: array
        title: notes
        example: '10'
        maximum: 10
        minimum: 4
        items:
            $ref: '#/components/schemas/Note'